services:
  execution:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    ports:
      - 22301:8545       # RPC
      - 22302:8546       # websocket
      - 22303:30303     # P2P TCP (currently unused)
      - 22303:30303/udp # P2P UDP (currently unused)
      - 22304:6060       # metrics
    command: [ "bash", "./execution-entrypoint" ]
    networks:
        - eth_shared_network
    volumes:
      - /root/base-chain-node/chain-data-sync/snapshots/mainnet/download/geth:/data
    env_file:
      # select your network here:
#      - .env.sepolia
      - .env.mainnet
  node:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    depends_on:
      - execution
    ports:
      - 22305:8545     # RPC
      - 22306:9222     # P2P TCP
      - 22306:9222/udp # P2P UDP
      - 22307:7300     # metrics
      - 22308:6060     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    networks:
        - eth_shared_network
    env_file:
      # select your network here:
#      - .env.sepolia
      - .env.mainnet

networks:
    eth_shared_network:
        external: true