services:
  execution:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    ports:
      - 39601:8545       # RPC
      - 39602:8546       # websocket
      - 39603:30303     # P2P TCP (currently unused)
      - 39603:30303/udp # P2P UDP (currently unused)
      - 39604:6060       # metrics
    command: [ "bash", "./execution-entrypoint" ]
    networks:
        - eth_shared_network
    volumes:
      - /data/chain-data/base-data/base-main-data/snapshots/mainnet/download/geth:/data
    env_file:
      # select your network here:
#      - .env.sepolia
      - .env.mainnet
  node:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    depends_on:
      - execution
    ports:
      - 39605:8545     # RPC
      - 39606:9222     # P2P TCP
      - 39606:9222/udp # P2P UDP
      - 39607:7300     # metrics
      - 39608:6060     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    networks:
        - eth_shared_network
    env_file:
      # select your network here:
#      - .env.sepolia
      - .env.mainnet

networks:
    eth_shared_network:
        external: true