version: '3.8'

services:
  base-prune:
    build:
      context: .
      dockerfile: ${CLIENT}/Dockerfile
    container_name: base-prune
    command: [ "bash", "-c", "/app/geth --datadir /data --db.engine=pebble --state.scheme=path --history.transactions=23500 --history.state=900 removedb --remove.state=false --remove.chain=true" ]
#    command: [ "bash", "-c", "/app/geth --datadir /data --db.engine=pebble --state.scheme=path --history.transactions=23500 --history.state=900 snapshot prune-state" ]
    networks:
      - eth_shared_network
    volumes:
      - /data/chain-data/base-data/base-main-data/snapshots/mainnet/download/geth:/data
    env_file:
      - .env.mainnet


networks:
  eth_shared_network:
    external: true
